### ISSUE TITLE
设置页滑动条的抖动

### ISSUE THREAD

**Issue by electron-shaders** [HanHan233/PhiCommunity#13]
# 运行环境

- 设备：Legion R9000P2021H

- 设备平台： Windows10 20H2 64位

- 浏览器：Microsoft Edge 99.0.1150.30

- 错误现象： 在电脑端浏览器打开设置页面，用鼠标按住拖动滑动条会出现奇怪的抖动。（为节约导出性能，录屏时调小了窗口大小，实际上此bug与窗口大小无关，但与是否为移动端有关）

https://user-images.githubusercontent.com/53993972/157252493-edb7de4a-bc9d-4855-b565-feadb8514144.mp4

https://user-images.githubusercontent.com/53993972/157252999-28df822d-f23f-4df2-a131-1e4b42c5e247.mp4

- 错误Log：见录屏

**Comment by electron-shaders** [comment]
此bug有一个细节是当鼠标划过并选中文字时，它得以暂时性地解决，但会在选中文字前后出现一个突变（具体见录屏1）

**Comment by HanHan233** [comment]
而关于移动端方面，我的认为是浏览器的仿真一般都只会仿真界面分辨率和userAgent，同时点击变为触摸，所以我认为此问题与是否为移动端无关

**Comment by electron-shaders** [comment]
log打印是因为offsetX的值不稳定的问题，改用移动端的公式就好了
