### ISSUE TITLE
建议新增站内谱面上传入口

### ISSUE THREAD

**Issue by electron-shaders** [HanHan233/PhiCommunity#15]
现在上传谱面的方式是跳转到github repo进行手动fork+pr，对于没用过github的人来说门槛较高，

因此可以通过在站内搭建一个上传页解决该问题。同时，上传页可以提供**预检验**功能，避免不必要的commit。

上传操作可考虑使用github oauth app + github api实现。

PS：如果可行的话我可以~~摸鱼~~帮忙贡献代码

**Comment by HanHan233** [comment]
虽然但是，这样的话多半需要暴露OAuth APP的api key（严重可能还要暴露我自身的TOKEN），否则就需要后端服务器来支持，或者使用cloudflare pages

**Comment by HanHan233** [comment]
你要说做一个入口，那肯定是能做的，只是没服务器储存而已

**Comment by Dreamail** [comment]
> 虽然但是，这样的话多半需要暴露OAuth APP的api key（严重可能还要暴露我自身的TOKEN），否则就需要后端服务器来支持，或者使用cloudflare pages

存本地cookie（

**Comment by HanHan233** [comment]
> > 虽然但是，这样的话多半需要暴露OAuth APP的api key（严重可能还要暴露我自身的TOKEN），否则就需要后端服务器来支持，或者使用cloudflare pages
> 
> 存本地cookie（

我个人认为，api key没有必要，也不应该存储于客户端

**Comment by electron-shaders** [comment]
oauth app的安全问题可以用阿里云的[函数计算](https://help.aliyun.com/document_detail/54301.html?spm=5176.137990.J_5253785160.6.50171608FUb8q5)解决，按量付费每月前100万次请求免费。

**Comment by HanHan233** [comment]
> oauth app的安全问题可以用阿里云的[函数计算](https://help.aliyun.com/document_detail/54301.html?spm=5176.137990.J_5253785160.6.50171608FUb8q5)解决，按量付费每月前100万次请求免费。

对于这个问题，先开发好上传界面再说吧，我们人还没开发好呢（

**Comment by YigeXiaogeziAwa** [comment]
> > oauth app的安全问题可以用阿里云的[函数计算](https://help.aliyun.com/document_detail/54301.html?spm=5176.137990.J_5253785160.6.50171608FUb8q5)解决，按量付费每月前100万次请求免费。
> 
> 对于这个问题，先开发好上传界面再说吧，我们人还没开发好呢（

最好还是让谱面作者自己上传，因为挺怕攻击的，我觉得最好的方法就是发一个教程图片吧

**Comment by YigeXiaogeziAwa** [comment]
> > oauth app的安全问题可以用阿里云的[函数计算](https://help.aliyun.com/document_detail/54301.html?spm=5176.137990.J_5253785160.6.50171608FUb8q5)解决，按量付费每月前100万次请求免费。
> 
> 对于这个问题，先开发好上传界面再说吧，我们人还没开发好呢（

顺带一提，我要准备开始学JavaScript了，毕竟一直提供tip也不是啥好的贡献方式qwq

**Comment by HanHan233** [comment]
> > > oauth app的安全问题可以用阿里云的[函数计算](https://help.aliyun.com/document_detail/54301.html?spm=5176.137990.J_5253785160.6.50171608FUb8q5)解决，按量付费每月前100万次请求免费。
> > 
> > 对于这个问题，先开发好上传界面再说吧，我们人还没开发好呢（
> 
> 顺带一提，我要准备开始学JavaScript了，毕竟一直提供tip也不是啥好的贡献方式qwq

建议学ts

**Comment by electron-shaders** [comment]
做了个界面出来，还没写逻辑（
![image](https://user-images.githubusercontent.com/53993972/158044517-c931b1f5-004d-459a-ba7f-ba58318ff453.png)

如果还不错的话我就接着干了？

**Comment by HanHan233** [comment]
> 做了个界面出来，还没写逻辑（
> ![image](https://user-images.githubusercontent.com/53993972/158044517-c931b1f5-004d-459a-ba7f-ba58318ff453.png)
> 
> 如果还不错的话我就接着干了？

其实我们好像有人在干了

**Comment by electron-shaders** [comment]
> 其实我们好像有人在干了

他进度怎么样了？如果我这版不错的话我就继续写了

**Comment by HanHan233** [comment]
我问问

**Comment by electron-shaders** [comment]
![image](https://user-images.githubusercontent.com/53993972/158067485-cb1e27d7-abb7-420f-8d14-4397bee13b2d.png)

完善了下自适应，现在界面弄好了（大概

**Comment by electron-shaders** [comment]
cao
