### ISSUE TITLE
tips对比度过低

### ISSUE THREAD

**Issue by electron-shaders** [HanHan233/PhiCommunity#23]
默认背景图片下，tips跟没显示一样，毫不明显。
![image](https://user-images.githubusercontent.com/53993972/157998911-ca2aa815-078c-442d-8875-e171dacff73f.png)

**Comment by electron-shaders** [comment]
顺便说一下，谱面仓库的网址还是旧的

**Comment by HanHan233** [comment]
> 顺便说一下，谱面仓库的网址还是旧的

啊？

**Comment by HanHan233** [comment]
改成黑色了

**Comment by electron-shaders** [comment]
> > 顺便说一下，谱面仓库的网址还是旧的
> 
> 啊？

是这个
![image](https://user-images.githubusercontent.com/53993972/158012523-88c8ed7a-49f7-4b12-b042-45c138d632ba.png)

**Comment by HanHan233** [comment]
已修改
