### ISSUE TITLE
[类似于BUG] 歌曲列表类似随机排序？

### ISSUE THREAD

**Issue by YigeXiaogeziAwa** [HanHan233/PhiCommunity#28]
在选择了不同的歌曲后刷新网页，歌曲列表会稍有变动，应该是随机的
网页大小1920x969px。

**Comment by HanHan233** [comment]
现在是并行获取歌曲meta列表，返回的速度各不相同，导致MetaList排列不同，所以排序会稍有变动，此问题不是Bug

**Comment by YigeXiaogeziAwa** [comment]
> 现在是并行获取歌曲meta列表，返回的速度各不相同，导致MetaList排列不同，所以排序会稍有变动，此问题不是Bug

好的
