### ISSUE TITLE
[体验优化] 加载速度太快导致tip无法完全看完，屏蔽一些按键

### ISSUE THREAD

**Issue by YigeXiaogeziAwa** [HanHan233/PhiCommunity#29]
加载速度太快tips根本很难完全看完（至少短的能看完）
建议等待几秒，因为加载速度只有3秒多，建议6秒后再进入游玩界面（

游玩过程中是所有按键都可以按到的，最好屏蔽一些按键，比如F11和ESC，我就有过怎么按F11都没有的感受（

**Comment by HanHan233** [comment]
浏览器原因，无法屏蔽/接管

**Comment by HanHan233** [comment]
（加载速度不能太快是真的第一次见）
