### ISSUE TITLE
建议整一个专门用于讨论PhiCommunity的聊天室

### ISSUE THREAD

**Issue by YigeXiaogeziAwa** [HanHan233/PhiCommunity#3]
有些人没有QQ（比如我），这个时候就可以搭建一个聊天室（这样没有qq的也能进去讨论，最重要的是有些人github进不去，可以整个bug讨论点啊！

你可以看下面的视频
https://www.bilibili.com/video/BV1RM4y1T7hz?from=search&seid=6674762588093655348&spm_id_from=333.337.0.0

**Comment by HanHan233** [comment]
整不了，没服务器（heroku那些懒得搞了）
而且应该也不怎么会普及
