### ISSUE TITLE
使用iPadOS 15.4游玩时出现黑屏bug

### ISSUE THREAD

**Issue by Emon14435** [HanHan233/PhiCommunity#31]
# 运行环境
设备：iPad Mini 5（iPadOS 15.4）
运行环境：iPadOS 15.4
问题：在safari中无法打开游玩界面，下载Edge后游玩界面能被打开并点击note，但是全过程无按键全黑屏。
log：没有mac抓不到log（摊手），有空找同学的来抓
![IMG_1980](https://user-images.githubusercontent.com/27557591/158839626-9ad3f14c-349c-4d63-9620-0636f382b288.PNG)
![IMG_1981](https://user-images.githubusercontent.com/27557591/158839643-4f4f6297-65c7-4559-8bb5-44c9d551a0e9.PNG)
（

**Comment by HanHan233** [comment]
试试夸克（？

**Comment by electron-shaders** [comment]
极有可能是开了深色模式的问题，我遇到过很多次canvas在深色模式下失效的问题（

**Comment by HanHan233** [comment]
确实，昨天就有个开深色模式判定线和note都消失的
