### ISSUE TITLE
这里的解析式到底是什么

### ISSUE THREAD

**Issue by DarthMikuH** [HanHan233/PhiCommunity#45]
<img width="1626" alt="截屏2022-10-16 上午11 33 31" src="https://user-images.githubusercontent.com/62818311/196016664-06b89c3c-9165-4cec-add6-b61cf4f03c60.png">
<img width="1642" alt="截屏2022-10-16 上午11 33 56" src="https://user-images.githubusercontent.com/62818311/196016683-1909c961-24de-480f-a711-5e7c5264964d.png">
真的看不清23333

**Comment by yuameshi** [comment]
我看了看，这个公式可能有点问题，图片中的公式是
```javascript
let f = (x) => (18111 / 2) * Math.pow(x, 4) - 90555 * Math.pow(x, 3) + (633885 / 2) * Math.pow(x, 2) - 452773 * x + 217331;
```
但是`f(5) !== 114514`，见下图

![image](https://user-images.githubusercontent.com/64469437/197950631-20c1f95c-b02a-482c-9f3c-53b44de639f2.png)
