### ISSUE TITLE
建议饭制谱收录之后发布个动态（如下图，可以找我制作

### ISSUE THREAD

**Issue by YigeXiaogeziAwa** [HanHan233/PhiCommunity#8]
![图片1](https://user-images.githubusercontent.com/100695614/156908558-ebffedfb-67a3-43c5-bff4-7eb89b2e2da0.png)

**Comment by YigeXiaogeziAwa** [comment]
测试用，使用了这logo和background的素材，你看怎么样（

**Comment by YigeXiaogeziAwa** [comment]
![图片1](https://user-images.githubusercontent.com/100695614/156912763-d045529d-5c5d-410b-bd49-1ebfa0f85a0f.png)
（重制版）

**Comment by YigeXiaogeziAwa** [comment]
![图片1](https://user-images.githubusercontent.com/100695614/156913321-ddce71f9-9e60-4a63-b7e2-c2f1d1e4e622.png)
重置版()

**Comment by HanHan233** [comment]
主要是，总不可能人家投稿一个就发一个吧，这不现实

**Comment by YigeXiaogeziAwa** [comment]
> 主要是，总不可能人家投稿一个就发一个吧，这不现实

忘记说了，可以一周发一次的，你觉得呢？记得回我

**Comment by HanHan233** [comment]
三个月或者一年还差不多（至少提交的人多了再说吧

**Comment by YigeXiaogeziAwa** [comment]
> 三个月或者一年还差不多（至少提交的人多了再说吧

好的，设计文件我留着，等到时候人多了再说吧，感谢大佬的信任ww

**Comment by HanHan233** [comment]
顺便就是说建议不要平行四边形，给这玩意儿整吐了（

**Comment by YigeXiaogeziAwa** [comment]
> 之后要搞肯定也是搞一个bot定时渲染发布，渲染我肯定是走HTML/Canvas（其他人提供方案那另说

草，bot也太麻烦了吧（

**Comment by HanHan233** [comment]
> > 之后要搞肯定也是搞一个bot定时渲染发布，渲染我肯定是走HTML/Canvas（其他人提供方案那另说
> 
> 草，bot也太麻烦了吧（

只发一两次肯定bot不好，但是如果以后都发那肯定是bot自动化好点

**Comment by YigeXiaogeziAwa** [comment]
> 之后要搞肯定也是搞一个bot定时渲染发布，渲染我肯定是走HTML/Canvas（其他人提供方案那另说

我觉得最好就是整个PhiCommunity账号，然后设置一个专门有人管的

**Comment by HanHan233** [comment]
> > 之后要搞肯定也是搞一个bot定时渲染发布，渲染我肯定是走HTML/Canvas（其他人提供方案那另说
> 
> 我觉得最好就是整个PhiCommunity账号，然后设置一个专门有人管的

没这么多手机号注册了，要发也只用我自己的账户发吧
