### ISSUE TITLE
选歌页面切换排序方式后滚动异常

### ISSUE THREAD

**Issue by electron-shaders** [HanHan233/PhiCommunity#9]
# 运行环境

- 设备：LegionR9000P 2021H
- 设备平台： Windows10(64位) 20H2

- 浏览器：Microsoft Edge 99.0.1150.30
![image](https://user-images.githubusercontent.com/53993972/156913951-1b98091c-b4b5-4995-92c0-bdc7c75acb0f.png)

- 错误现象： 如GIF，切换排序方式后将以之前选择的元素作为滚动窗口上界，导致无法正常滚动
https://user-images.githubusercontent.com/53993972/156914659-14e7a4fe-af45-42ad-b652-8e68ffe7b491.mp4

- 错误Log：无

**Comment by HanHan233** [comment]
原因已经查明，此Bug将在下个提交修复（最慢下周六）
